### ISSUE TITLE
Vary height of `org-verbatim` and `org-code` faces in org-mode headings

### ISSUE THREAD

**Issue by stevemolitor** [protesilaos/ef-themes#10]
This may not be possible, but it'd be nice if verbatim and code sections in org-mode headings changed their size along with the `variable-pitch` font. He's an exaggerated example:

```emacs-lisp
(setq
 ef-themes-headings
 '((1 . (5.0)))
 ef-themes-mixed-fonts t
 ef-themes-variable-pitch-ui t)
```

Org file:

![](https://cdn.zappy.app/280e4dc2bffafd14cd70004ed7695b2b.png)

**Comment by protesilaos** [comment]
Hello @stevemolitor!

This is an Org issue.  Though it has been solved upstream since maybe Org version 9.3.  What does `M-x org-version` give you?

This is how it looks on my end:

![Screenshot from 2022-08-26 04-09-40](https://user-images.githubusercontent.com/12828033/186795227-e8be523d-7f7e-491c-af39-298cf97f4e98.png)

It is the same with and without `variable-pitch`.

**Comment by stevemolitor** [comment]
Hi @protesilaos thanks for the response and sorry to bug you with an Org issue. 

I'm using org `9.5.4`: 

```
Org mode version 9.5.4 (9.5.4-g99681c @ /Users/stephenmolitor/.emacs.d/straight/build/org/)
```

I'll see if it's something on my end via `emacs -q`, and if not file an issue with Org.

Sorry for the noise.

**Comment by protesilaos** [comment]
@stevemolitor since you are on the latest Org version, the only other explanation is that you are using an absolute `:height` value for your `fixed-pitch` face.  Please check your font settings and I can explain more.

**Comment by protesilaos** [comment]
You are welcome!  Closing this issue now.
