### ISSUE TITLE
The value of `ef-themes-headings` doesn't seem to change the appearance of headings

### ISSUE THREAD

**Issue by joncol** [protesilaos/ef-themes#15]
Hi again!

I'm using the following configuration:
```emacs-lisp
(setq ef-themes-headings '((1 . (rainbow overline background))))
```

The appearance of headers is like:
![ef-summer](https://user-images.githubusercontent.com/194062/188115962-a9455dfb-2f6f-43f7-b142-57f6b25aa508.png)

I expected something like (screenshot taken using your `modus-vivendi` theme):
![modus-vivendi](https://user-images.githubusercontent.com/194062/188116053-c4d2e377-094c-44ef-8ddd-23d7ea04882b.png)

In the below screenshot the "blocks" for level 1 headings are clearly visible.

**Comment by protesilaos** [comment]
Hi @joncol!  This is because the `ef-themes-headings` only has a subset of the stylistic variants of `modus-themes-headings`.  Basically, it only affects the fonts: height, weight, and use of `variable-pitch`.

Sample with this:

```elisp
  (setq ef-themes-headings ; read the manual's entry of the doc string
        '((0 . (variable-pitch light 1.9))
          (1 . (variable-pitch light 1.8))
          (2 . (variable-pitch light 1.7))
          (3 . (variable-pitch semilight 1.6))
          (4 . (variable-pitch semilight 1.5))
          (5 . (variable-pitch regular 1.4))
          (6 . (variable-pitch regular 1.3))
          (7 . (variable-pitch 1.2))    ; absence of weight means `bold'
          (t . (variable-pitch 1.1))))
```

![Screenshot from 2022-09-02 13-13-12](https://user-images.githubusercontent.com/12828033/188117892-0cfe1665-31fa-44d1-9ffa-f234ce50a29a.png)

The reason for not affecting colour combinations is because those will be exponentially more difficult in the Ef themes.  We have lots of themes, each of which has its own colour mapping.

As for the `rainbow`, in particular, it is how the Ef themes do it by default (whereas the Modus themes have a more austere look).

**Comment by joncol** [comment]
I see, thanks for the response. Closing this issue then.
